name: anime_streaming_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  dio: ^5.0.0
  cached_network_image: ^3.2.1
  video_player: ^2.2.18
  carousel_slider: ^5.0.0   # For featured anime carousel
  google_fonts: ^6.2.1      # For custom fonts


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
